apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    cloud.google.com/backend-config: "{\"default\": \"{{ .Values.frontend.backendConfig }}\"}"
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000