apiVersion: v1
kind: Service
metadata:
  name: espv2-service
spec:
  type: ClusterIP
  selector:
    app: espv2
  ports:
  - port: {{ .Values.espv2.service.port }}
    targetPort: {{ .Values.espv2.service.targetPort }}
    protocol: TCP